#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Login Module Manifest
# -----------------------------------------------------------------------------

MODULE_NAME="login"
MODULE_DESCRIPTION="User Login Activity Monitoring"
MODULE_VERSION="1.0"

MODULE_DEPENDS=()

MODULE_SERVICES=(
    lsm-login.service
    lsm-login.timer
)
