#!/usr/bin/env bash
# ==============================================================================
# Lite Server Monitor (LSM)
# Метаданные модуля UPS
# ==============================================================================


MODULE_ID="ups"

MODULE_NAME="Мониторинг UPS"

MODULE_DESCRIPTION="Контроль состояния источника бесперебойного питания"

MODULE_VERSION="1.0"

MODULE_CATEGORY="hardware"


MODULE_DEPENDENCIES=""

MODULE_REQUIRED_PACKAGES="apcupsd"


MODULE_SERVICE="lsm-ups.service"

MODULE_TIMER="lsm-ups.timer"
