#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Temperature Module Manifest
# -----------------------------------------------------------------------------

MODULE_NAME="temperature"
MODULE_DESCRIPTION="CPU and System Temperature Monitoring"
MODULE_VERSION="1.0"

MODULE_DEPENDS=()

MODULE_SERVICES=(
    lsm-temperature.service
    lsm-temperature.timer
)
