#!/usr/bin/env bash
# ==============================================================================
# Lite Server Monitor (LSM)
# Метаданные модуля System
# ==============================================================================

MODULE_ID="system"

MODULE_NAME="System Base"

MODULE_DESCRIPTION="Базовая настройка Linux системы, пользователи, окружение и системные параметры."

MODULE_VERSION="1.0.0"

MODULE_CATEGORY="core"

MODULE_DEPENDENCIES=""

MODULE_REQUIRED_PACKAGES="
bash
coreutils
"

MODULE_SERVICE=""

MODULE_TIMER=""
