# -----------------------------------------------------------------------------
# Lite Server Monitor
# Disk Module Configuration
# -----------------------------------------------------------------------------

WARNING=80
CRITICAL=90

IGNORE_MOUNTS=(
    "/boot"
    "/snap"
)
