#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# SMART Configuration
# -----------------------------------------------------------------------------

#
# Ignore devices
#

IGNORE_DEVICES=""

#
# Send notification immediately after SMART failure
#

NOTIFY_ON_FAILURE=true

#
# Enable temperature reporting if available
#

REPORT_TEMPERATURE=true
