#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Temperature Configuration
# -----------------------------------------------------------------------------

#
# Maximum allowed CPU temperature (°C)
#

WARNING_TEMP=70
CRITICAL_TEMP=80

#
# Notifications
#

NOTIFY_ON_WARNING=true
NOTIFY_ON_RECOVERY=true
