# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM) - Module Status
# -----------------------------------------------------------------------------

MODULE_SYSTEM="enabled"
MODULE_DISK="enabled"
MODULE_SMART="enabled"
MODULE_LOGIN="enabled"

MODULE_RAID="disabled"
MODULE_UPS="disabled"
MODULE_FAIL2BAN="disabled"
MODULE_TEMPERATURE="disabled"
