# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM) - Sensitive Secrets
# Этот файл при установке получает права доступа 600 (chmod 600)
# -----------------------------------------------------------------------------

# Пароль приложения для SMTP (Email)
SMTP_PASSWORD=""
