# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM) - Global Default Thresholds
# -----------------------------------------------------------------------------

# Нагрузка на CPU (%)
CPU_WARN=80
CPU_CRIT=90

# Использование RAM (%)
RAM_WARN=85
RAM_CRIT=95

# Заполнение дисков (%)
DISK_WARN=85
DISK_CRIT=95

# Порог температуры CPU (°C)
TEMP_WARN=75
TEMP_CRIT=85
