#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# UPS Configuration
# -----------------------------------------------------------------------------

#
# Battery threshold
#

BATTERY_WARNING=50
BATTERY_CRITICAL=20


#
# Runtime threshold (minutes)
#

RUNTIME_WARNING=10


#
# Notifications
#

NOTIFY_ON_BATTERY=true
NOTIFY_ON_LOW_BATTERY=true
NOTIFY_ON_RECOVERY=true
