# ==============================================================================
# Lite Server Monitor (LSM)
# Метаданные модуля
# ==============================================================================

MODULE_ID="core"

MODULE_NAME="Ядро LSM"

MODULE_DESCRIPTION="Базовые функции системы мониторинга и общие зависимости"

MODULE_VERSION="1.0.0"

MODULE_CATEGORY="system"

MODULE_DEPENDENCIES=""

MODULE_DEFAULT="yes"
