#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Fail2Ban Module Manifest
# -----------------------------------------------------------------------------

MODULE_NAME="fail2ban"
MODULE_DESCRIPTION="Fail2Ban Protection Monitoring"
MODULE_VERSION="1.0"

MODULE_DEPENDS=(
    fail2ban
)

MODULE_SERVICES=(
    lsm-fail2ban.service
    lsm-fail2ban.timer
)
